#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
export GOPATH="/home/anthony/Documents/go"
export PATH=$PATH:$GOPATH/bin
. /usr/lib/z.sh

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less' 
#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
export SSH_ASKPASS="/usr/bin/ksshaskpass"
export LIB_AS_UTILS_HOME="/home/anthony/Documents/cpp_lib/libasutils"
export GTEST_HOME="/home/anthony/Documents/cpp_lib/googletest/googletest"
export BOOST_CPP_HOME="/home/anthony/Documents/cpp_lib/boost_1_61_0"
export LIB_MICROHTTP_HOME="/home/anthony/Documents/cpp_lib/libmicrohttpd-0.9.52/build"
export LIB_LOG4CPP_HOME="/home/anthony/Documents/cpp_lib/log4cpp/build"
export LIB_UUID_HOME="/home/anthony/Documents/cpp_lib/libuuid-1.0.3/build"

export LD_LIBRARYPATH=$LD_LIBRARY_PATH:$LIB_UUID_HOME/lib/
export LD_LIBRARYPATH=$LD_LIBRARY_PATH:$LIB_LOG4CPP_HOME/lib/
export LD_LIBRARYPATH=$LD_LIBRARY_PATH:$LIB_MICROHTTP_HOME/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$BOOST_CPP_HOME/stage/lib/

