#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source "$HOME/.zprezto/modules/prompt/functions/prompt_bureau_setup" red green yellow


# Aliases
# List directory contents
alias sl=ls
alias ls='ls -G'        # Compact view, show colors
alias la='ls -AF'       # Compact view, show hidden
alias ll='ls -al'
alias q='exit'

if [ $(uname) = "Linux" ]
then
  alias ls="ls --color=auto"
fi

# Custom aliases
alias gitc='git commit -am $1'
alias gitp='git push'
alias update='yay -Syu --noconfirm'

# Network aliases
alias myip='curl http://ipecho.net/plain; echo'

# Location aliases
alias uci='cd ~/Dropbox/My\ Documents/school_stuff/'
alias lab='ssh anthonml@openlab.ics.uci.edu'
alias aer='cd ~/Dropbox/My\ Documents/Aerserv'

# Language aliases

alias ..='cd ..'         # Go up one directory
alias ...='cd ../..'     # Go up two directories
alias ....='cd ../../..' # Go up three directories
alias -- -='cd -'        # Go back

# Locations
source /etc/profile.d/vte.sh
