#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source "$HOME/.zprezto/modules/prompt/functions/prompt_bureau_setup" red green yellow


# Aliases
# List directory contents
alias ls='exa -G'        # Compact view, show colors
alias la='ls -AF'       # Compact view, show hidden
alias ll='exa -al'
alias q='exit'

alias _="sudo"

alias bhtunnel="sshuttle --dns -r anthony.lam@bh.aerserv.com 10.0.0.0/16"

if [ $(uname) = "Linux" ]
then
  alias ls="exa"
fi

# EXPORTS
export PYTHONPATH="/Users/anthonylam/Documents/qa/qa-utils/"
export GOPATH="/Users/anthonylam/Documents/go"
export PATH="/opt/liquibase":"/home/anthony/.config/redis-trib":"$GOPATH/bin":$PATH
export PATH="/usr/local/anaconda3/bin":$PATH
. "/usr/local/etc/profile.d/z.sh"

eval "$(rbenv init -)"
